controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
nelmio_api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger
api_login_check:
    path: /api/login